/* generated by tools/generate.py — do not edit */
#pragma once
#include "rpc/messages.h"

void rpc_register_all(void);

/* Implement any of these to handle incoming messages.
   Weak no-ops are provided — only override what you need. */
void rpc_handle_led_toggle_green(void);
void rpc_handle_led_toggle_red(void);
void rpc_handle_set_gain(const set_gain_t *msg);
