/* generated by tools/generate.py — do not edit */
#include "rpc/rpc_generated.h"
#include "rpc/rpc.h"
#include <stddef.h>

/* -- Weak default handlers ------------------------------------------ */

__attribute__((weak)) void rpc_handle_led_toggle_green(void) {}
__attribute__((weak)) void rpc_handle_led_toggle_red(void) {}
__attribute__((weak)) void rpc_handle_set_gain(const set_gain_t *msg) { (void)msg; }

/* -- Dispatch shims ------------------------------------------------- */

static void _on_led_toggle_green(uint8_t id, const uint8_t *buf, size_t len)
{
    (void)id; (void)buf; (void)len;
    rpc_handle_led_toggle_green();
}

static void _on_led_toggle_red(uint8_t id, const uint8_t *buf, size_t len)
{
    (void)id; (void)buf; (void)len;
    rpc_handle_led_toggle_red();
}

static void _on_set_gain(uint8_t id, const uint8_t *buf, size_t len)
{
    (void)id;
    if (len >= sizeof(set_gain_t)) rpc_handle_set_gain((const set_gain_t *)buf);
}

/* -- Registration --------------------------------------------------- */

void rpc_register_all(void)
{
#ifdef CORE_CM4
    rpc_register(MSG_LED_TOGGLE_GREEN, DEST_CM4, _on_led_toggle_green);
    rpc_register(MSG_LED_TOGGLE_RED, DEST_CM7, NULL);
    rpc_register(MSG_SET_GAIN, DEST_CM7, NULL);
#endif
#ifdef CORE_CM7
    rpc_register(MSG_LED_TOGGLE_RED, DEST_CM7, _on_led_toggle_red);
    rpc_register(MSG_SET_GAIN, DEST_CM7, _on_set_gain);
#endif
}
