#!/usr/bin/env python3
"""
Generate RPC message definitions from proto/messages.yaml.

Outputs:
    include/messages.h          — C enum + packed structs
    src/rpc/generated/rpc_generated.h     — rpc_register_all() + typed handler declarations
    src/rpc/generated/rpc_generated.c     — weak defaults + dispatch shims + rpc_register_all()
    tools/host/rpc_messages.py  — Python dataclasses with pack/unpack + COBS codec

Usage:
    python tools/codegen/generate.py
"""

import sys
import textwrap
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML required:  pacman -S mingw-w64-ucrt-x86_64-python-yaml")

ROOT    = Path(__file__).parent.parent.parent   # tools/codegen -> tools -> repo root
SCHEMA  = ROOT / "proto" / "messages.yaml"

C_TYPES = {
    "uint8":   "uint8_t",
    "uint16":  "uint16_t",
    "uint32":  "uint32_t",
    "int8":    "int8_t",
    "int16":   "int16_t",
    "int32":   "int32_t",
    "float32": "float",
}

PY_FMT = {
    "uint8":   "B",
    "uint16":  "H",
    "uint32":  "I",
    "int8":    "b",
    "int16":   "h",
    "int32":   "i",
    "float32": "f",
}

def snake_to_camel(s: str) -> str:
    return "".join(w.capitalize() for w in s.split("_"))

def snake_to_upper(s: str) -> str:
    return s.upper()

def msg_enum(name: str) -> str:
    return f"MSG_{snake_to_upper(name)}"

def struct_name(name: str) -> str:
    return f"{name}_t"

def handler_name(name: str) -> str:
    return f"rpc_handle_{name}"

def shim_name(name: str) -> str:
    return f"_on_{name}"


_VALID_DESTS = {"host", "cm4", "cm7", "both"}
_VALID_TYPES = set(C_TYPES.keys())


def validate(msgs: list) -> None:
    """Fail fast with a clear message if messages.yaml has structural errors."""
    ids_seen: set = set()
    for m in msgs:
        for key in ("id", "name", "dest"):
            if key not in m:
                raise ValueError(f"message {m} is missing required field '{key}'")
        name = m["name"]
        if m["dest"] not in _VALID_DESTS:
            raise ValueError(f"'{name}' has invalid dest '{m['dest']}' (must be one of {sorted(_VALID_DESTS)})")
        if not (0 <= m["id"] <= 0xFF):
            raise ValueError(f"'{name}' id 0x{m['id']:x} is out of uint8 range")
        if m["id"] in ids_seen:
            raise ValueError(f"duplicate id 0x{m['id']:02x} on message '{name}'")
        ids_seen.add(m["id"])
        for f in m.get("fields", []):
            for fkey in ("name", "type"):
                if fkey not in f:
                    raise ValueError(f"field in '{name}' is missing required key '{fkey}'")
            if f["type"] not in _VALID_TYPES:
                raise ValueError(
                    f"'{name}.{f['name']}' has unknown type '{f['type']}' "
                    f"(valid: {sorted(_VALID_TYPES)})"
                )


def gen_messages_h(msgs: list) -> str:
    lines = [
        "/* generated by tools/generate.py \u2014 do not edit */",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "typedef enum {",
    ]

    for m in msgs:
        lines.append(f"    {msg_enum(m['name']):<24} = 0x{m['id']:02x},")

    lines += ["} msg_id_t;", ""]

    has_payload = [m for m in msgs if m.get("fields")]
    no_payload  = [m for m in msgs if not m.get("fields")]

    for m in has_payload:
        parts = " ".join(C_TYPES[f["type"]] + " " + f["name"] + ";" for f in m["fields"])
        lines.append(f"typedef struct __attribute__((packed)) {{ {parts} }} {struct_name(m['name'])};")

    if no_payload:
        lines.append("")
        names = ", ".join(msg_enum(m["name"]) for m in no_payload)
        lines.append(f"/* {names}: no payload — pass NULL, 0. */")

    lines.append("")
    return "\n".join(lines)


def gen_rpc_generated_h(msgs: list) -> str:
    receivable = [m for m in msgs if m["dest"] != "host"]

    lines = [
        "/* generated by tools/generate.py — do not edit */",
        "#pragma once",
        '#include "messages.h"',
        "",
        "void rpc_register_all(void);",
        "",
        "/* Implement any of these to handle incoming messages.",
        "   Weak no-ops are provided — only override what you need. */",
    ]

    for m in receivable:
        dest  = m["dest"]
        guard = "CORE_CM4" if dest == "cm4" else "CORE_CM7" if dest == "cm7" else None
        if guard:
            lines.append(f"#ifdef {guard}")
        if m.get("fields"):
            lines.append(f"void {handler_name(m['name'])}(const {struct_name(m['name'])} *msg);")
        else:
            lines.append(f"void {handler_name(m['name'])}(void);")
        if guard:
            lines.append(f"#endif /* {guard} */")

    lines.append("")
    return "\n".join(lines)


def gen_rpc_generated_c(msgs: list) -> str:
    receivable = [m for m in msgs if m["dest"] != "host"]

    lines = [
        "/* generated by tools/generate.py — do not edit */",
        '#include "rpc/generated/rpc_generated.h"',
        '#include "rpc/rpc.h"',
        '#include "rpc/rpc_config.h"',
        "#include <stddef.h>",
        "",
        "/* -- Weak default handlers ------------------------------------------ */",
        "",
    ]

    for m in receivable:
        dest  = m["dest"]
        guard = "CORE_CM4" if dest == "cm4" else "CORE_CM7" if dest == "cm7" else None
        if guard:
            lines.append(f"#ifdef {guard}")
        if m.get("fields"):
            lines.append(f"__attribute__((weak)) void {handler_name(m['name'])}(const {struct_name(m['name'])} *msg) {{ (void)msg; }}")
        else:
            lines.append(f"__attribute__((weak)) void {handler_name(m['name'])}(void) {{}}")
        if guard:
            lines.append(f"#endif /* {guard} */")

    lines += ["", "/* -- Dispatch shims ------------------------------------------------- */", ""]

    for m in receivable:
        dest  = m["dest"]
        guard = "CORE_CM4" if dest == "cm4" else "CORE_CM7" if dest == "cm7" else None
        if guard:
            lines.append(f"#ifdef {guard}")
        lines.append(f"static void {shim_name(m['name'])}(uint8_t id, const uint8_t *buf, size_t len)")
        lines.append("{")
        if m.get("fields"):
            sn = struct_name(m["name"])
            lines.append(f"    (void)id;")
            lines.append(f"    if (len >= sizeof({sn})) {handler_name(m['name'])}((const {sn} *)buf);")
        else:
            lines.append(f"    (void)id; (void)buf; (void)len;")
            lines.append(f"    {handler_name(m['name'])}();")
        lines.append("}")
        if guard:
            lines.append(f"#endif /* {guard} */")
        lines.append("")

    lines += ["/* -- Registration --------------------------------------------------- */", ""]
    lines.append("void rpc_register_all(void)")
    lines.append("{")

    # CM4 block
    cm4_msgs = [m for m in msgs if m["dest"] in ("cm4", "both")]
    cm4_fwd  = [m for m in msgs if m["dest"] in ("cm7", "both")]
    if cm4_msgs or cm4_fwd:
        lines.append("#ifdef CORE_CM4")
        for m in cm4_msgs:
            dest = "DEST_BOTH" if m["dest"] == "both" else "DEST_CM4"
            lines.append(f"    rpc_register({msg_enum(m['name'])}, {dest}, {shim_name(m['name'])});")
        for m in cm4_fwd:
            if m["dest"] == "cm7":  # both already covered above
                lines.append(f"    rpc_register({msg_enum(m['name'])}, DEST_CM7, NULL);")
        lines.append("#endif")

    # CM7 block
    cm7_msgs = [m for m in msgs if m["dest"] in ("cm7", "both")]
    if cm7_msgs:
        lines.append("#ifdef CORE_CM7")
        for m in cm7_msgs:
            dest = "DEST_BOTH" if m["dest"] == "both" else "DEST_CM7"
            lines.append(f"    rpc_register({msg_enum(m['name'])}, {dest}, {shim_name(m['name'])});")
        lines.append("#endif")

    lines.append("}")
    lines.append("")

    # Payload size guards — live here, not in messages.h, because RPC_FRAME_MAX_PAYLOAD
    # is a transport concern, not a message definition concern.
    has_payload = [m for m in msgs if m.get("fields")]
    if has_payload:
        lines.append("/* -- Payload size guards ------------------------------------------- */")
        lines.append("")
        for m in has_payload:
            sn = struct_name(m["name"])
            lines.append(f'_Static_assert(sizeof({sn}) <= RPC_FRAME_MAX_PAYLOAD, "{sn} exceeds RPC_FRAME_MAX_PAYLOAD");')
        lines.append("")

    return "\n".join(lines)


def gen_rpc_messages_py(msgs: list) -> str:
    lines = [
        "# generated by tools/generate.py \u2014 do not edit",
        "import struct",
        "from dataclasses import dataclass, field",
        "from typing import ClassVar",
        "",
    ]

    # Embed the COBS codec so callers only need to import this one module.
    lines += [
        "",
        "# \u2500\u2500 COBS framing \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
        "",
        "def cobs_encode(data: bytes) -> bytes:",
        '    """COBS-encode data. Returns encoded bytes without the 0x00 frame terminator."""',
        "    out = bytearray()",
        "    i = 0",
        "    while True:",
        "        block_start = len(out)",
        "        out.append(0)",
        "        code = 1",
        "        while i < len(data) and data[i] != 0x00:",
        "            out.append(data[i])",
        "            i += 1",
        "            code += 1",
        "            if code == 0xFF:",
        "                out[block_start] = code",
        "                code = 1",
        "                block_start = len(out)",
        "                out.append(0)",
        "        out[block_start] = code",
        "        if i >= len(data):",
        "            break",
        "        i += 1",
        "    return bytes(out)",
        "",
        "",
        "def cobs_decode(data: bytes) -> bytes:",
        '    """COBS-decode a frame (without its 0x00 terminator). Raises ValueError on malformed input."""',
        "    out = bytearray()",
        "    i = 0",
        "    while i < len(data):",
        "        code = data[i]; i += 1",
        "        if code == 0:",
        '            raise ValueError("unexpected 0x00 inside COBS frame")',
        "        for _ in range(code - 1):",
        "            if i >= len(data):",
        '                raise ValueError("truncated COBS block")',
        "            out.append(data[i]); i += 1",
        "        if code < 0xFF and i < len(data):",
        "            out.append(0x00)",
        "    return bytes(out)",
        "",
        "",
        "def make_frame(msg_id: int, payload: bytes) -> bytes:",
        '    """Build a complete framed packet: COBS(msg_id || payload) + 0x00 terminator."""',
        "    return cobs_encode(bytes([msg_id]) + payload) + b'\\x00'",
        "",
        "",
        "# \u2500\u2500 Message classes \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
        "",
    ]

    for m in msgs:
        class_name = snake_to_camel(m["name"])
        fields     = m.get("fields", [])
        fmt        = "<" + "".join(PY_FMT[f["type"]] for f in fields)

        lines.append("@dataclass")
        lines.append(f"class {class_name}:")
        lines.append(f"    MSG_ID: ClassVar[int] = 0x{m['id']:02x}")

        for f in fields:
            py_type = "float" if f["type"] == "float32" else "int"
            fname, ftype = f["name"], py_type
            lines.append(f"    {fname}: {ftype} = 0")

        lines.append("")
        lines.append("    @classmethod")
        lines.append(f"    def unpack(cls, data: bytes) -> '{class_name}':")
        if fields:
            names = ", ".join(f["name"] for f in fields)
            kwargs = ", ".join(f["name"] + "=" + f["name"] for f in fields)
            lines.append(f"        {names}, = struct.unpack_from('{fmt}', data)")
            lines.append(f"        return cls({kwargs})")
        else:
            lines.append(f"        return cls()")

        lines.append("")
        lines.append("    def pack(self) -> bytes:")
        if fields:
            args = ", ".join("self." + f["name"] for f in fields)
            lines.append(f"        return struct.pack('{fmt}', {args})")
        else:
            lines.append("        return b''")

        lines.append("")
        lines.append("")

    class_names = [snake_to_camel(m["name"]) for m in msgs]
    lines.append("REGISTRY: dict[int, type] = {")
    for m, cn in zip(msgs, class_names):
        lines.append(f"    0x{m['id']:02x}: {cn},")
    lines.append("}")
    lines.append("")
    lines.append("")
    lines.append("def decode_frame(msg_id: int, payload: bytes):")
    lines.append("    cls = REGISTRY.get(msg_id)")
    lines.append("    return cls.unpack(payload) if cls else None")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    schema = yaml.safe_load(SCHEMA.read_text())
    msgs   = schema["messages"]

    validate(msgs)

    outputs = {
        ROOT / "include" / "messages.h":            gen_messages_h(msgs),
        ROOT / "src" / "rpc" / "generated" / "rpc_generated.h": gen_rpc_generated_h(msgs),
        ROOT / "src" / "rpc" / "generated" / "rpc_generated.c": gen_rpc_generated_c(msgs),
        ROOT / "tools" / "host" / "rpc_messages.py": gen_rpc_messages_py(msgs),
    }

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"  wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
