# generated by tools/generate.py — do not edit
import struct
from dataclasses import dataclass, field
from typing import ClassVar


# ── COBS framing ───────────────────────────────────────────────────────

def cobs_encode(data: bytes) -> bytes:
    """COBS-encode data. Returns encoded bytes without the 0x00 frame terminator."""
    out = bytearray()
    i = 0
    while True:
        block_start = len(out)
        out.append(0)
        code = 1
        while i < len(data) and data[i] != 0x00:
            out.append(data[i])
            i += 1
            code += 1
            if code == 0xFF:
                out[block_start] = code
                code = 1
                block_start = len(out)
                out.append(0)
        out[block_start] = code
        if i >= len(data):
            break
        i += 1
    return bytes(out)


def cobs_decode(data: bytes) -> bytes:
    """COBS-decode a frame (without its 0x00 terminator). Raises ValueError on malformed input."""
    out = bytearray()
    i = 0
    while i < len(data):
        code = data[i]; i += 1
        if code == 0:
            raise ValueError("unexpected 0x00 inside COBS frame")
        for _ in range(code - 1):
            if i >= len(data):
                raise ValueError("truncated COBS block")
            out.append(data[i]); i += 1
        if code < 0xFF and i < len(data):
            out.append(0x00)
    return bytes(out)


def make_frame(msg_id: int, payload: bytes) -> bytes:
    """Build a complete framed packet: COBS(msg_id || payload) + 0x00 terminator."""
    return cobs_encode(bytes([msg_id]) + payload) + b'\x00'


# ── Message classes ──────────────────────────────────────────────────────────

@dataclass
class HeartbeatCm4:
    MSG_ID: ClassVar[int] = 0x01
    seq: int = 0

    @classmethod
    def unpack(cls, data: bytes) -> 'HeartbeatCm4':
        seq, = struct.unpack_from('<I', data)
        return cls(seq=seq)

    def pack(self) -> bytes:
        return struct.pack('<I', self.seq)


@dataclass
class HeartbeatCm7:
    MSG_ID: ClassVar[int] = 0x02
    seq: int = 0

    @classmethod
    def unpack(cls, data: bytes) -> 'HeartbeatCm7':
        seq, = struct.unpack_from('<I', data)
        return cls(seq=seq)

    def pack(self) -> bytes:
        return struct.pack('<I', self.seq)


@dataclass
class LedToggleGreen:
    MSG_ID: ClassVar[int] = 0x10

    @classmethod
    def unpack(cls, data: bytes) -> 'LedToggleGreen':
        return cls()

    def pack(self) -> bytes:
        return b''


@dataclass
class LedToggleRed:
    MSG_ID: ClassVar[int] = 0x11

    @classmethod
    def unpack(cls, data: bytes) -> 'LedToggleRed':
        return cls()

    def pack(self) -> bytes:
        return b''


@dataclass
class SetGain:
    MSG_ID: ClassVar[int] = 0x20
    channel: int = 0
    gain_db: float = 0

    @classmethod
    def unpack(cls, data: bytes) -> 'SetGain':
        channel, gain_db, = struct.unpack_from('<Bf', data)
        return cls(channel=channel, gain_db=gain_db)

    def pack(self) -> bytes:
        return struct.pack('<Bf', self.channel, self.gain_db)


@dataclass
class PeakMeter:
    MSG_ID: ClassVar[int] = 0x80
    channel: int = 0
    peak_db: float = 0

    @classmethod
    def unpack(cls, data: bytes) -> 'PeakMeter':
        channel, peak_db, = struct.unpack_from('<Bf', data)
        return cls(channel=channel, peak_db=peak_db)

    def pack(self) -> bytes:
        return struct.pack('<Bf', self.channel, self.peak_db)


REGISTRY: dict[int, type] = {
    0x01: HeartbeatCm4,
    0x02: HeartbeatCm7,
    0x10: LedToggleGreen,
    0x11: LedToggleRed,
    0x20: SetGain,
    0x80: PeakMeter,
}


def decode_frame(msg_id: int, payload: bytes):
    cls = REGISTRY.get(msg_id)
    return cls.unpack(payload) if cls else None
