# generated by tools/generate.py — do not edit
import struct
from dataclasses import dataclass, field
from typing import ClassVar

@dataclass
class HeartbeatCm4:
    MSG_ID: ClassVar[int] = 0x01
    seq: int = 0

    @classmethod
    def unpack(cls, data: bytes) -> 'HeartbeatCm4':
        seq, = struct.unpack_from('<I', data)
        return cls(seq=seq)

    def pack(self) -> bytes:
        return struct.pack('<I', self.seq)


@dataclass
class HeartbeatCm7:
    MSG_ID: ClassVar[int] = 0x02
    seq: int = 0

    @classmethod
    def unpack(cls, data: bytes) -> 'HeartbeatCm7':
        seq, = struct.unpack_from('<I', data)
        return cls(seq=seq)

    def pack(self) -> bytes:
        return struct.pack('<I', self.seq)


@dataclass
class LedToggleGreen:
    MSG_ID: ClassVar[int] = 0x10

    @classmethod
    def unpack(cls, data: bytes) -> 'LedToggleGreen':
        return cls()

    def pack(self) -> bytes:
        return b''


@dataclass
class LedToggleRed:
    MSG_ID: ClassVar[int] = 0x11

    @classmethod
    def unpack(cls, data: bytes) -> 'LedToggleRed':
        return cls()

    def pack(self) -> bytes:
        return b''


@dataclass
class SetGain:
    MSG_ID: ClassVar[int] = 0x20
    channel: int = 0
    gain_db: float = 0

    @classmethod
    def unpack(cls, data: bytes) -> 'SetGain':
        channel, gain_db, = struct.unpack_from('<Bf', data)
        return cls(channel=channel, gain_db=gain_db)

    def pack(self) -> bytes:
        return struct.pack('<Bf', self.channel, self.gain_db)


@dataclass
class PeakMeter:
    MSG_ID: ClassVar[int] = 0x80
    channel: int = 0
    peak_db: float = 0

    @classmethod
    def unpack(cls, data: bytes) -> 'PeakMeter':
        channel, peak_db, = struct.unpack_from('<Bf', data)
        return cls(channel=channel, peak_db=peak_db)

    def pack(self) -> bytes:
        return struct.pack('<Bf', self.channel, self.peak_db)


REGISTRY: dict[int, type] = {
    0x01: HeartbeatCm4,
    0x02: HeartbeatCm7,
    0x10: LedToggleGreen,
    0x11: LedToggleRed,
    0x20: SetGain,
    0x80: PeakMeter,
}


def decode_frame(msg_id: int, payload: bytes):
    cls = REGISTRY.get(msg_id)
    return cls.unpack(payload) if cls else None
