/* generated by tools/generate.py — do not edit */
/* clang-format off */
#include "src/rpc_generated.h"
#include "src/rpc.h"
#include "protocol/rpc_types.h"
#include <stddef.h>

/* -- Weak default handlers ------------------------------------------ */

__attribute__((weak)) void rpc_handle_led_toggle_green(void) {}
__attribute__((weak)) void rpc_handle_led_toggle_red(void) {}
__attribute__((weak)) void rpc_handle_set_gain(const set_gain_t *msg) { (void)msg; }

/* -- Dispatch shims (private) --------------------------------------- */

static void _on_led_toggle_green(uint8_t id, const uint8_t *buf, size_t len)
{
    (void)id; (void)buf; (void)len;
    rpc_handle_led_toggle_green();
}

static void _on_led_toggle_red(uint8_t id, const uint8_t *buf, size_t len)
{
    (void)id; (void)buf; (void)len;
    rpc_handle_led_toggle_red();
}

static void _on_set_gain(uint8_t id, const uint8_t *buf, size_t len)
{
    (void)id;
    if (len >= sizeof(set_gain_t)) rpc_handle_set_gain((const set_gain_t *)buf);
}

/* -- Per-message registration functions ----------------------------- */

void rpc_register_led_toggle_green(rpc_dest_t dest)
{
    rpc_register(MSG_LED_TOGGLE_GREEN, dest, _on_led_toggle_green);
}

void rpc_register_led_toggle_red(rpc_dest_t dest)
{
    rpc_register(MSG_LED_TOGGLE_RED, dest, _on_led_toggle_red);
}

void rpc_register_set_gain(rpc_dest_t dest)
{
    rpc_register(MSG_SET_GAIN, dest, _on_set_gain);
}

/* -- Typed transmit helpers ----------------------------------------- */

int rpc_transmit_heartbeat_cm4(const heartbeat_cm4_t *msg)
{
    return rpc_transmit(MSG_HEARTBEAT_CM4, msg, sizeof(*msg));
}

int rpc_transmit_heartbeat_cm7(const heartbeat_cm7_t *msg)
{
    return rpc_transmit(MSG_HEARTBEAT_CM7, msg, sizeof(*msg));
}

int rpc_transmit_peak_meter(const peak_meter_t *msg)
{
    return rpc_transmit(MSG_PEAK_METER, msg, sizeof(*msg));
}

/* -- Payload size guards ------------------------------------------- */

_Static_assert(sizeof(set_gain_t) <= RPC_FRAME_MAX_PAYLOAD, "set_gain_t exceeds RPC_FRAME_MAX_PAYLOAD");
_Static_assert(sizeof(heartbeat_cm4_t) <= RPC_FRAME_MAX_PAYLOAD, "heartbeat_cm4_t exceeds RPC_FRAME_MAX_PAYLOAD");
_Static_assert(sizeof(heartbeat_cm7_t) <= RPC_FRAME_MAX_PAYLOAD, "heartbeat_cm7_t exceeds RPC_FRAME_MAX_PAYLOAD");
_Static_assert(sizeof(peak_meter_t) <= RPC_FRAME_MAX_PAYLOAD, "peak_meter_t exceeds RPC_FRAME_MAX_PAYLOAD");
